#!/usr/bin/env python3
"""Generate native Bash entry points beside executable PowerShell scripts."""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
LEGACY_BASH_ROOT = REPO_ROOT / "scripts" / "platform" / "bash"
GENERATED_MARKER = "# Generated by scripts/tools/generate-bash-launchers.py; do not edit."
NATIVE_ENTRY_POINTS = {
    REPO_ROOT / "scripts" / "run-pipeline.ps1",
    REPO_ROOT / "scripts" / "portal" / "build-portal-offline.ps1",
    REPO_ROOT / "scripts" / "phases" / "phase-A-chunk.ps1",
    REPO_ROOT / "scripts" / "phases" / "phase-B-facts.ps1",
    REPO_ROOT / "scripts" / "phases" / "phase-C-extract-text.ps1",
    REPO_ROOT / ".github" / "skills" / "cobol-chunking" / "scripts" / "chunk_batch.ps1",
    REPO_ROOT / ".github" / "skills" / "cobol-facts-extraction" / "scripts" / "extract_facts_batch.ps1",
    REPO_ROOT / ".github" / "skills" / "chunk-text-extraction" / "scripts" / "extract_chunks_batch.ps1",
}
POWERSHELL_LIBRARIES = {
    REPO_ROOT / "scripts" / "lib" / name
    for name in (
        "Convert-MdToDocx.ps1",
        "Invoke-CopilotDispatch.ps1",
        "Invoke-PythonBatch.ps1",
        "Resolve-EffectiveGroupingManifest.ps1",
        "Resolve-PhaseInputs.ps1",
        "aggregate-results.ps1",
    )
}

SKILL_MODES = {
    "slice_facts_batch.ps1": "slice_facts",
    "write_sections_batch.ps1": "write_sections",
    "finalize_stage_batch.ps1": "finalize_stage",
    "assemble_complete_batch.ps1": "assemble_complete",
    "diagrams_stage_batch.ps1": "diagrams_stage",
    "req_stage_batch.ps1": "req_stage",
    "req_finalize_stage_batch.ps1": "req_finalize_stage",
    "fa_stage_batch.ps1": "fa_stage",
    "fa_finalize_stage_batch.ps1": "fa_finalize_stage",
    "ta_stage_batch.ps1": "ta_stage",
    "req_group_stage_batch.ps1": "req_group_stage",
    "fa_group_stage_batch.ps1": "fa_group_stage",
    "group_doc_stage_batch.ps1": "group_doc_stage",
    "ta_group_stage_batch.ps1": "ta_group_stage",
}

DISPATCH_MODES = {
    "run-docs-copilot-batch.ps1": "section",
    "run-docs-diagrams-batch.ps1": "diagrams",
    "run-docs-finalize-batch.ps1": "finalize",
    "run-docs-req-section-batch.ps1": "req-section",
    "run-docs-req-finalize-batch.ps1": "req-finalize",
    "run-docs-fa-section-batch.ps1": "fa-section",
    "run-docs-fa-finalize-batch.ps1": "fa-finalize",
    "run-docs-group-doc-finalize-batch.ps1": "group-doc-finalize",
    "run-docs-req-group-section-batch.ps1": "req-group-section",
    "run-docs-req-group-finalize-batch.ps1": "req-group-finalize",
    "run-docs-fa-group-section-batch.ps1": "fa-group-section",
    "run-docs-fa-group-finalize-batch.ps1": "fa-group-finalize",
    "run-docs-ta-finalize-batch.ps1": "ta-finalize",
    "run-docs-ta-group-finalize-batch.ps1": "ta-group-finalize",
}


def discover() -> dict[Path, Path]:
    scripts = list((REPO_ROOT / "scripts").rglob("*.ps1"))
    scripts.extend((REPO_ROOT / ".github" / "skills").glob("*/scripts/*.ps1"))
    return {
        script_path.with_suffix(".sh"): script_path
        for script_path in sorted(set(scripts))
        if script_path not in NATIVE_ENTRY_POINTS and script_path not in POWERSHELL_LIBRARIES
    }


def render(destination: Path, script_path: Path) -> str:
    relative = script_path.relative_to(REPO_ROOT).as_posix()
    if script_path.name in SKILL_MODES:
        target = "scripts/lib/native-skill-batch.sh"
        mode = SKILL_MODES[script_path.name]
    elif script_path.name in DISPATCH_MODES:
        target = "scripts/lib/native-copilot-dispatch.sh"
        mode = DISPATCH_MODES[script_path.name]
    elif relative.startswith("scripts/phases/phase-"):
        target = "scripts/lib/native-phase.sh"
        mode = script_path.name.removeprefix("phase-").split("-", 1)[0]
    else:
        raise ValueError(f"No native Bash mode for {relative}")
    return f"""#!/usr/bin/env bash
{GENERATED_MARKER}
set -euo pipefail

readonly script_dir="$(cd -- "$(dirname -- "${{BASH_SOURCE[0]}}")" && pwd)"
readonly repo_root="$(cd -- "${{script_dir}}/{'/'.join(['..'] * len(destination.relative_to(REPO_ROOT).parent.parts))}" && pwd)"
exec "${{repo_root}}/{target}" {mode} "$@"
"""


def generated_launchers() -> list[Path]:
    launchers: list[Path] = []
    for root in (REPO_ROOT / "scripts", REPO_ROOT / ".github" / "skills"):
        for candidate in root.rglob("*.sh"):
            try:
                first_lines = candidate.read_text(encoding="utf-8").splitlines()[:2]
            except OSError:
                continue
            if GENERATED_MARKER in first_lines:
                launchers.append(candidate)
    return launchers


def check(mappings: dict[Path, Path]) -> int:
    problems: list[str] = []
    expected_paths = set(mappings)
    for destination, script_path in mappings.items():
        expected = render(destination, script_path)
        if not destination.exists():
            problems.append(f"missing: {destination.relative_to(REPO_ROOT)}")
        elif destination.read_text(encoding="utf-8") != expected:
            problems.append(f"stale: {destination.relative_to(REPO_ROOT)}")

    for candidate in generated_launchers():
        if candidate not in expected_paths:
            problems.append(f"orphan: {candidate.relative_to(REPO_ROOT)}")
    if LEGACY_BASH_ROOT.exists():
        problems.append(f"legacy directory: {LEGACY_BASH_ROOT.relative_to(REPO_ROOT)}")

    if problems:
        print("Bash launcher drift:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1
    print(f"Native Bash entry points OK: {len(mappings)} generated, {len(NATIVE_ENTRY_POINTS)} maintained")
    return 0


def generate(mappings: dict[Path, Path]) -> int:
    expected_paths = set(mappings)
    for candidate in generated_launchers():
        if candidate not in expected_paths:
            candidate.unlink()
    if LEGACY_BASH_ROOT.exists():
        shutil.rmtree(LEGACY_BASH_ROOT)

    for destination, script_path in mappings.items():
        destination.write_text(render(destination, script_path), encoding="utf-8", newline="\n")
    print(f"Generated {len(mappings)} native Bash entry points")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when launchers are missing or stale")
    args = parser.parse_args()
    mappings = discover()
    return check(mappings) if args.check else generate(mappings)


if __name__ == "__main__":
    raise SystemExit(main())