#!/usr/bin/env bash
# Generated by scripts/tools/generate-bash-launchers.py; do not edit.
set -euo pipefail

readonly script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly repo_root="$(cd -- "${script_dir}/../../../.." && pwd)"
exec "${repo_root}/scripts/lib/native-skill-batch.sh" ta_stage "$@"
